apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools
  namespace: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
        - name: cicd-tools
          image: itzconnor/cicd-tools
          volumeMounts:
            - name: cicd-volume
              mountPath: /shared_data
          command: [ "/bin/bash" ]
          args:
            - -c
            - "cp -R /cicd/* /shared_data/ && touch /shared_data/copy.done"
      volumes:
        - name: cicd-volume
          emptyDir: {}