apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools
  namespace: deploy
spec:
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
        - name: cicd-tools
          image: itzconnor/cicd-tools
          command: [ "/bin/bash" ]